### ISSUE TITLE
Would you mind adding some minimal docs?

### ISSUE THREAD

**Issue by endrebak** [ksahlin/GetDistr#3]
I want to compute the avg. frag size for single end reads in a bed file. Can this script do it? If so, how? What are the Python version and external package reqs? Any required external programs?

Thanks.

**Comment by ksahlin** [comment]
No, the scripts are only for calculating insert size/fragmnet length of paired reads in different "scenarios" described in http://biorxiv.org/content/biorxiv/early/2015/08/04/023929.full.pdf. The "getdistr/model.py" is the script supposed to contain functions for doing this and one could use that as a module.
I will add documentation, proper setup.py including dependencies, and more asap.

Thanks for putting some pressure on me to clean up the mess! :)

Best,
Kristoffer

**Comment by ksahlin** [comment]
Ok, so now I have added some documentation in the README.md and I'm closing this.
Thanks,
Kristoffer
